# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Raffaele Di Fazio
tagline:          'Raffaele Di Fazio Blog.'
description:      'A blog about life and tech. Mainly English content, sometimes some Italian will appear.'
url:              http://twitter.com/x0rg 
baseurl:          http://raffo.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

linkedin:         https://it.linkedin.com/pub/raffaele-di-fazio/39/b87/453
twitter:          https://twitter.com/x0rg

github:
  repo:           https://github.com/Raffo
